<h3> This is Jun Su's qmaster data test. </h3>

Before reading the data, warming up for data frame <code>df</code>

In [2]:
import pandas as pd

df=pd.DataFrame({'a':[11,21,31],'b':[21,22,23]})

1) plot the first three rows:

In [3]:
df.head(3)

    a   b
0  11  21
1  21  22
2  31  23

2) obtain column  <code> 'a' </code>

In [4]:
df['a']

0    11
1    21
2    31
Name: a, dtype: int64

In [6]:
df.iloc[1,0]

21

<h3>Reading qmaster data</h3>

In [12]:
qMasterFile='/Users/kr050496/q.dat.test'
qdf=pd.read_csv(qMasterFile,sep='|',delimiter=None,header=0)

Show the first few lines.

In [13]:
qdf.head()

,TIME,EMPNO,NAME,CASE_TYPE,LINK,WORK_TYPE,AREA,IGNORE
0,2016-01-01 15:57:42,379509,JunSu-Lee,DB2FTS,"<a href=""https://w3-01.sso.ibm.com/software/se...",A,EP,<BR>
1,2016-01-01 17:49:52,373706,Will-Sun,DB2FTS,"<a href=""https://w3-01.sso.ibm.com/software/se...",T,EP,<BR>
2,2016-01-01 17:58:27,379509,JunSu-Lee,DB2FTS,"<a href=""https://w3-01.sso.ibm.com/software/se...",t,EP,<BR>
3,2016-01-02 14:17:38,378836,Yogesh-Gawali,DB2FTS,"<a href=""https://w3-01.sso.ibm.com/software/se...",T,EP,<BR>
4,2016-01-03 13:00:24,919707,Xia-Ning-Zhang,DB2FTS,"<a href=""https://w3-01.sso.ibm.com/software/se...",T,CC,<BR>

Show selecting interested columns.

In [17]:
qdf[['EMPNO','NAME']]

        EMPNO            NAME
0      379509       JunSu-Lee
1      373706        Will-Sun
2      379509       JunSu-Lee
3      378836   Yogesh-Gawali
4      919707  Xia-Ning-Zhang
...       ...             ...
11516  374145  Priyanka-Joshi
11517  379456      Ajay-Patil
11518  378836   Yogesh-Gawali
11519  360996      Haibo-Wang
11520  374145  Priyanka-Joshi

[11521 rows x 2 columns]

<hr>
<small>Copyright &copy; 2020 IBM Cognitive Class. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license/).</small>

In [20]:
qdf['NAME'].unique()

array(['JunSu-Lee', 'Will-Sun', 'Yogesh-Gawali', 'Xia-Ning-Zhang',
       'Jian-Tang', 'Priyanka-Joshi', 'Shashank-Kharche', 'Fang-Zheng',
       'Chee-Hoe-Quek', 'Woong-Choi', 'Chun-Gao', 'Haibo-Wang',
       'Ajay-Patil', 'James-Ji', 'Juilee-Hapse', 'Malcolm-Blunt',
       'Yuki-Terai', 'Ken-Tsuchiya', 'Hidehiro-Yamanaka', 'Makoto-Oda',
       'Akihiro-Kobayashi', 'Fufei-Xu', 'Chie-Nakayama', 'Akane-Kohno',
       'Hisanori-Harada', 'Yilei-Wang', 'Kenta-Hoshino',
       'Masato-Sadachika', 'Hiroaki-Nakatsubo', 'Hiromichi-Shinozaki',
       'Kanishka-Mandal', 'Devesh-Tripathi', 'Milind-Dumbhare',
       'Rohit-Raut', 'Jie-Zhang'], dtype=object)

In [32]:
qdf2020 = qdf[qdf['TIME'] >= '2020']
qdf2020

,TIME,EMPNO,NAME,CASE_TYPE,LINK,WORK_TYPE,AREA,IGNORE
9534,2020-01-01 12:29:11,379509,JunSu-Lee,APWTPB,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,PS,<BR>
9535,2020-01-01 12:32:27,880254,Woong-Choi,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,PF,<BR>
9536,2020-01-01 12:32:43,379509,JunSu-Lee,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,QE,<BR>
9537,2020-01-01 15:53:43,379456,Ajay-Patil,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,DM,<BR>
9538,2020-01-01 15:54:29,379456,Ajay-Patil,APWTPB,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,DDG,<BR>
...,...,...,...,...,...,...,...,...
11516,2020-09-27 14:41:47,374145,Priyanka-Joshi,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,CORE2_PMODEL,<BR>
11517,2020-09-27 14:42:10,379456,Ajay-Patil,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,AV,<BR>
11518,2020-09-27 14:42:39,378836,Yogesh-Gawali,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,DDG,<BR>
11519,2020-09-27 15:39:45,360996,Haibo-Wang,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,US,<BR>
11520,2020-09-27 15:40:18,374145,Priyanka-Joshi,DB2FTS,"<a href=""https://ibm-case-viewer.w3ibm.mybluem...",T,DM,<BR>